import {
    Shoe1,
    Shoe2,
    Shoe3,
    Shoe4,
    Shoe5,
    TwoShoe1,
    TwoShoe2,
    TwoShoe3,
    TwoShoe4,
    TwoShoe5,
    TwoShoe6,
    threeShoe1,
    threeShoe2,
    threeShoe3,
    threeShoe4,
    fourShoe1,
    fourShoe2,
    fourShoe3,
    fourShoe4,
    fourShoe5,
    fiveShoe1,
    fiveShoe2,
    fiveShoe3,
    fiveShoe4,
} from "../allProducts/images";

export const products = [{
        URL: "FD0736-102",
        imgURL: Shoe1,
        imgURLs: [Shoe1, Shoe2, Shoe3, Shoe4, Shoe5],
        name: "Nike V2k Run",
        price: 4699,
        description: "erkek kadın unısex sneaker koşu ayakkabısı",
        rate: 4.7,
        specious: "Sneaker",
    },
    {
        URL: "FV6519_200",
        imgURL: TwoShoe1,
        imgURLs: [TwoShoe1, TwoShoe2, TwoShoe3, TwoShoe4, TwoShoe5, TwoShoe6],
        name: "Nike Air Force 1",
        description: "erkek kadın unısex sneaker koşu ayakkabısı",
        specious: "Sneaker",
        price: 130,
        rate: 4.6,
    },
    {
        URL: "DV3808-107",
        imgURL: threeShoe1,
        imgURLs: [threeShoe1, threeShoe2, threeShoe3, threeShoe4],
        name: "Nike Air Force 1 '07 Se",
        description: "Kadın Ayakkabısı",
        price: 4699,
        rate: 4.4,
    },
    {
        URL: "CD6404-103",
        imgURL: fourShoe1,
        imgURLs: [fourShoe1, fourShoe2, fourShoe3, fourShoe4, fourShoe5],
        name: "Nike P-6000",
        price: 200,
        description: "erkek kadın unısex sneaker koşu ayakkabısı",
        rate: 4.8,
        specious: "Sneaker",
    },
    {
        URL: "FZ5630_101",
        imgURL: fiveShoe1,
        imgURLs: [fiveShoe1, fiveShoe2, fiveShoe3, fiveShoe4],
        name: "Nike Killshot 2",
        price: 3699,
        description: "kadın sneaker",
        specious: "Sneaker",
        rate: 4.5,
    },
    {
        URL: "FZ3773_100",
        imgURL: Shoe4,
        imgURLs: [
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0173419_nike-w-air-force-1-shadow-fz3773-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0173421_nike-w-air-force-1-shadow-fz3773-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0173424_nike-w-air-force-1-shadow-fz3773-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0173425_nike-w-air-force-1-shadow-fz3773-100.jpeg",
        ],
        name: "Nike W Air Force 1 Shadow",
        price: 4699,
        description: "kadın sneaker",
        specious: "Sneaker",
        rate: 3.9,
    },
    {
        URL: "shoe7",
        imgURL: Shoe4,
        imgURLs: [
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0148189_nike-w-cortez-dn1791-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0148190_nike-w-cortez-dn1791-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0148192_nike-w-cortez-dn1791-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0148193_nike-w-cortez-dn1791-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0148194_nike-w-cortez-dn1791-100.jpeg",
        ],
        name: "Nike Cortez Leather",
        price: 1949,
        description: "kadın sneaker",
        specious: "Sneaker",
        rate: 4.1,
    },
    {
        URL: "DV0833_108",
        imgURL: Shoe4,
        imgURLs: [
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0197621_nike-dunk-low-retro-dv0833-108.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0197624_nike-dunk-low-retro-dv0833-108.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0197622_nike-dunk-low-retro-dv0833-108.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0197627_nike-dunk-low-retro-dv0833-108.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0197626_nike-dunk-low-retro-dv0833-108.jpeg",
        ],
        name: "Nike Dunk Low Retro",
        price: 4699,
        description: "erkek sneaker",
        specious: "Sneaker",
        rate: 4.2,
    },
    {
        URL: "DV0833_100",
        imgURL: Shoe4,
        imgURLs: [
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0144679_nike-dunk-low-retro-bttys-dv0833-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0144680_nike-dunk-low-retro-bttys-dv0833-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0144681_nike-dunk-low-retro-bttys-dv0833-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0144682_nike-dunk-low-retro-bttys-dv0833-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0144683_nike-dunk-low-retro-bttys-dv0833-100.jpeg",
        ],
        name: "Nike Dunk Low Retro",
        price: 4699,
        description: "erkek sneaker",
        specious: "Sneaker",
        rate: 4.3,
    },
    {
        URL: "DV0833_104",
        imgURL: Shoe4,
        imgURLs: [
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0186982_nike-dunk-low-retro-bttys-dv0833-104.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0186983_nike-dunk-low-retro-bttys-dv0833-104.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0186984_nike-dunk-low-retro-bttys-dv0833-104.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0186985_nike-dunk-low-retro-bttys-dv0833-104.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0186987_nike-dunk-low-retro-bttys-dv0833-104.jpeg",
        ],
        name: "Nike Dunk Low Retro",
        price: 4699,
        description: "erkek sneaker",
        specious: "Sneaker",
        rate: 4.6,
    },
    // // 10 additional products
    {
        URL: "FV7275_401",
        imgURL: Shoe4,
        imgURLs: [
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0192918_nike-lebron-xxi-premium-fv7275-401.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0192919_nike-lebron-xxi-premium-fv7275-401.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0192920_nike-lebron-xxi-premium-fv7275-401.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0192922_nike-lebron-xxi-premium-fv7275-401.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0192924_nike-lebron-xxi-premium-fv7275-401.jpeg",
        ],
        name: "Nike Lebron XXI Premium",
        price: 8999,
        description: "erkek basketbol ayakkabısı",
        specious: "Sneaker",
        rate: 4.5,
    },
    {
        URL: "FQ8249_100",
        imgURL: Shoe4,
        imgURLs: [
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0193340_nike-dunk-low-retro-se-fq8249-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0193343_nike-dunk-low-retro-se-fq8249-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0193346_nike-dunk-low-retro-se-fq8249-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0193348_nike-dunk-low-retro-se-fq8249-100.jpeg",
            "https://img-sneaksupincommerce.mncdn.com/Content/Images/Thumbs/0193350_nike-dunk-low-retro-se-fq8249-100.jpeg",
        ],
        name: "Nike Dunk Low Retro SE",
        price: 4699,
        description: "erkek sneaker",
        specious: "Sneaker",
        rate: 4.7,
    },
];